# Generated by Django 3.2.12 on 2022-06-04 13:41

from django.db import migrations, models
import people.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_year']},
        ),
        migrations.AddField(
            model_name='event',
            name='event_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='marriage',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=people.fields.UncertainDateField(null=True),
        ),
    ]
