# Generated by Django 3.2.12 on 2022-06-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20220604_0741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_year',
        ),
        migrations.RemoveField(
            model_name='marriage',
            name='year',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Nacimiento'), (1, 'Bautizo'), (3, 'Defunción'), (4, 'Sepelio')]),
        ),
    ]
